### ISSUE TITLE
Fails to install on civi 5.19.0, drupal 7.67

### ISSUE THREAD

**Issue by grischard** [civicrm/org.civicrm.mosaicomsgtpl#14]
```
$ cv dl -f org.civicrm.mosaicomsgtpl@https://github.com/civicrm/org.civicrm.mosaicomsgtpl/archive/master.zip
Using extension feed "https://civicrm.org/extdir/ver=5.19.0|uf=Drupal|status=stable|ready=ready"
Downloading extension "org.civicrm.mosaicomsgtpl" (https://github.com/civicrm/org.civicrm.mosaicomsgtpl/archive/master.zip)
Error: API Call Failed: Array
(
    [entity] => Extension
    [action] => download
    [params] => Array
        (
            [key] => org.civicrm.mosaicomsgtpl
            [url] => https://github.com/civicrm/org.civicrm.mosaicomsgtpl/archive/master.zip
            [install] => 1
            [debug] => 1
            [version] => 3
        )

    [result] => Array
        (
            [trace] => #0 /var/www/civitest/sites/default/files/civicrm/ext/org.civicrm.mosaicomsgtpl/CRM/Mosaicomsgtpl/Upgrader.php(55): civicrm_api3('Job', 'mosaico_msg_syn...', Array)
#1 /var/www/civitest/sites/default/files/civicrm/ext/org.civicrm.mosaicomsgtpl/CRM/Mosaicomsgtpl/Upgrader/Base.php(350): CRM_Mosaicomsgtpl_Upgrader->enable()
#2 /var/www/civitest/sites/default/files/civicrm/ext/org.civicrm.mosaicomsgtpl/mosaicomsgtpl.civix.php(170): CRM_Mosaicomsgtpl_Upgrader_Base->onEnable()
#3 /var/www/civitest/sites/default/files/civicrm/ext/org.civicrm.mosaicomsgtpl/mosaicomsgtpl.php(70): _mosaicomsgtpl_civix_civicrm_enable()
#4 /var/www/civitest/sites/all/modules/civicrm/CRM/Extension/Manager/Module.php(76): mosaicomsgtpl_civicrm_enable()
#5 /var/www/civitest/sites/all/modules/civicrm/CRM/Extension/Manager/Module.php(49): CRM_Extension_Manager_Module->callHook(Object(CRM_Extension_Info), 'enable')
#6 /var/www/civitest/sites/all/modules/civicrm/CRM/Extension/Manager.php(264): CRM_Extension_Manager_Module->onPreInstall(Object(CRM_Extension_Info))
#7 /var/www/civitest/sites/all/modules/civicrm/api/v3/Extension.php(258): CRM_Extension_Manager->install(Array)
#8 /var/www/civitest/sites/all/modules/civicrm/Civi/API/Provider/MagicFunctionProvider.php(101): civicrm_api3_extension_download(Array)
#9 /var/www/civitest/sites/all/modules/civicrm/Civi/API/Kernel.php(168): Civi\API\Provider\MagicFunctionProvider->invoke(Array)
#10 /var/www/civitest/sites/all/modules/civicrm/Civi/API/Kernel.php(99): Civi\API\Kernel->runRequest(Array)
#11 /var/www/civitest/sites/all/modules/civicrm/api/api.php(23): Civi\API\Kernel->runSafe('Extension', 'download', Array, NULL)
#12 phar:///usr/local/bin/cv/src/Command/BaseCommand.php(49): civicrm_api('Extension', 'download', Array)
#13 phar:///usr/local/bin/cv/src/Command/ExtensionDownloadCommand.php(141): Civi\Cv\Command\BaseCommand->callApiSuccess(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput), 'Extension', 'download', Array)
#14 phar:///usr/local/bin/cv/vendor/symfony/console/Command/Command.php(257): Civi\Cv\Command\ExtensionDownloadCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 phar:///usr/local/bin/cv/vendor/symfony/console/Application.php(850): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 phar:///usr/local/bin/cv/vendor/symfony/console/Application.php(193): Symfony\Component\Console\Application->doRunCommand(Object(Civi\Cv\Command\ExtensionDownloadCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 phar:///usr/local/bin/cv/src/Application.php(46): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 phar:///usr/local/bin/cv/vendor/symfony/console/Application.php(124): Civi\Cv\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 phar:///usr/local/bin/cv/src/Application.php(15): Symfony\Component\Console\Application->run()
#20 phar:///usr/local/bin/cv/bin/cv(27): Civi\Cv\Application::main('phar:///usr/loc...')
#21 /usr/local/bin/cv(10): require('phar:///usr/loc...')
#22 {main}
            [is_error] => 1
            [error_message] => API (MosaicoTemplate, get) does not exist (join the API team and implement it!)
        )

)
```

This happens even after clearing all the caches.

**Comment by MikeyMJCO** [comment]
I think this is related to civicrm/civicrm-core/pull/15766 - I cannot reproduce with the patch in that PR installed, I can only reproduce with the patch missing. This will be fixed in core 5.19.1 or by the referenced patch.

**Comment by grischard** [comment]
Indeed, I can't reproduce this in 5.19.1 either. Thank you!

**Comment by MikeyMJCO** [comment]
Thanks for coming back and updating this @grischard - much appreciated :-)
